name: Check-in

on:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间0点（即北京时间5点）触发

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 指定Python版本
    - name: Install dependencies
      run: pip install helium  # 安装依赖
    - name: Run check-in script
      run: |
        python caih.py  # 运行签到脚本
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCOUNTS_PATH: accounts.txt  # 账号密码文件路径
