name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install helium
        
        
    - name: Get IP address
      run: echo ${GITHUB_EVENT_CLIENT_IP}



    - name: Run caih.py
      run: |
        python caih.py
