name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Chrome and ChromeDriver
      run: |
        $latest_chromedriver_version = (Invoke-WebRequest -UseBasicParsing -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE").Content.Trim()
        Invoke-WebRequest -UseBasicParsing -Uri "https://dl.google.com/chrome/install/standalone/enterprise/GoogleChromeEnterprise.msi" -OutFile "chrome.msi"
        Start-Process msiexec.exe -ArgumentList "/i chrome.msi /quiet /qn /norestart /log install.log" -Wait
        Invoke-WebRequest -UseBasicParsing -Uri "https://chromedriver.storage.googleapis.com/$latest_chromedriver_version/chromedriver_win32.zip" -OutFile "chromedriver_win32.zip"
        Expand-Archive -Path chromedriver_win32.zip -DestinationPath .
        Move-Item -Path .\chromedriver.exe -Destination C:\Windows\System32\chromedriver.exe

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install helium

    - name: Run caih.py
      run: |
        python caih.py
