name: Python package

on:
  schedule:
  - cron: '0 */5 * * *'  # 每天 UTC 时间 5:00 运行

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install webdriver_manager
        python -m pip install helium

    - name: Install chromedriver
      run: |
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
        
    - name: Print Chrome version
      run: google-chrome --version


    - name: Run caih.py
      run: |
        python caih.py
