name: Python package

on:
  schedule:
  - cron: '0 */5 * * *'  # 每天 UTC 时间 5:00 运行

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install webdriver_manager
        python -m pip install helium
        python -m pip install selenium

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072 #TLS 1.2
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
    - name: Install Chrome and ChromeDriver
      run: |
        choco install googlechrome chromedriver -y

    - name: Check ChromeDriver version
      run: chromedriver --version



    - name: Run caih.py
      run: |
        python caih.py
